name: jot_notes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  firebase_storage: ^12.1.0
  path: ^1.9.0
  image_picker: ^1.1.2
  rich_text_controller: ^2.0.1
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  firebase_ui_auth: ^1.15.0
  sign_in_button: ^3.0.0
  firebase_cached_image: ^0.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  pigeon: ^21.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/camus.jpg


